var memories = [ 
{ "name" : "bag of human waste"}, 
{ "name" : "Apollo 12 plaque"}, 
{ "name" : "Apollo 13 plaque"}, 
{ "name" : "Apollo 14 plaque"}, 
{ "name" : "Apollo 15 plaque"}, 
{ "name" : "Apollo 16 plaque"}, 
{ "name" : "Apollo 17 plaque"}, 
{ "name" : "US flag"}, 
{ "name" : "golf ball"}, 
{ "name" : "retroreflector"}, 
{ "name" : "ALSEP"}, 
{ "name" : "EASEP"}, 
{ "name" : "footprint"}, 
{ "name" : "the Bible left by David Scott"}, 
{ "name" : "silver astronaut pin left by Alan Bean"}, 
{ "name" : "goodwill messages disc"}, 
{ "name" : "The Fallen Astronaut memorial"}]; 